import 'package:flutter/material.dart';
import 'package:flutterapp/vegaapp/generatedsplashwidget/generated/GeneratedButtonWidget2.dart';
import 'package:flutterapp/vegaapp/generatedsplashwidget/generated/GeneratedGetsthingsdonewithTODOWidget.dart';
import 'package:flutterapp/vegaapp/generatedsplashwidget/generated/GeneratedSuccessisnotfinalfailureisnotfatalItisthecouragetoconti.dart';
import 'package:flutterapp/vegaapp/generatedsplashwidget/generated/GeneratedShapeWidget3.dart';
import 'package:flutterapp/vegaapp/generatedsplashwidget/generated/GeneratedNotificationWidget4.dart';
import 'package:flutterapp/vegaapp/generatedsplashwidget/generated/GeneratedNotificationWidget3.dart';
import 'package:flutterapp/vegaapp/generatedsplashwidget/generated/GeneratedUndraw_mobile_ux_o0e11Widget.dart';

/* Frame splash
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 246, 246, 246),
                ),
              ),
              Positioned(
                left: -99.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 270.0,
                child: GeneratedShapeWidget3(),
              ),
              Positioned(
                left: 25.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 324.6666564941406,
                height: 16.0,
                child: GeneratedNotificationWidget3(),
              ),
              Positioned(
                left: 25.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 324.6666564941406,
                height: 16.0,
                child: GeneratedNotificationWidget4(),
              ),
              Positioned(
                left: 102.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 172.556396484375,
                height: 170.0,
                child: GeneratedUndraw_mobile_ux_o0e11Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 435.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 23.0,
                child: GeneratedGetsthingsdonewithTODOWidget(),
              ),
              Positioned(
                left: 48.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 56.0,
                child:
                    GeneratedSuccessisnotfinalfailureisnotfatalItisthecouragetoconti(),
              ),
              Positioned(
                left: 26.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 62.0,
                child: GeneratedButtonWidget2(),
              )
            ]),
      ),
    ));
  }
}
