import 'package:flutter/material.dart';
import 'package:flutterapp/vegaapp/generatedregistrationwidget/generated/GeneratedWelcomeOnboardWidget.dart';
import 'package:flutterapp/vegaapp/generatedregistrationwidget/generated/GeneratedInputWidget4.dart';
import 'package:flutterapp/vegaapp/generatedregistrationwidget/generated/GeneratedButtonWidget1.dart';
import 'package:flutterapp/vegaapp/generatedregistrationwidget/generated/GeneratedInputWidget2.dart';
import 'package:flutterapp/vegaapp/generatedregistrationwidget/generated/GeneratedNotificationWidget2.dart';
import 'package:flutterapp/vegaapp/generatedregistrationwidget/generated/GeneratedLetshelpyoumeetupyourtasksWidget.dart';
import 'package:flutterapp/vegaapp/generatedregistrationwidget/generated/GeneratedShapeWidget2.dart';
import 'package:flutterapp/vegaapp/generatedregistrationwidget/generated/GeneratedInputWidget3.dart';
import 'package:flutterapp/vegaapp/generatedregistrationwidget/generated/GeneratedAlreadyhaveanaccountSignInWidget.dart';
import 'package:flutterapp/vegaapp/generatedregistrationwidget/generated/GeneratedInputWidget5.dart';

/* Frame registration
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistrationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 246, 246, 246),
                ),
              ),
              Positioned(
                left: -99.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 270.0,
                child: GeneratedShapeWidget2(),
              ),
              Positioned(
                left: 25.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 324.6666564941406,
                height: 16.0,
                child: GeneratedNotificationWidget2(),
              ),
              Positioned(
                left: 92.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 23.0,
                child: GeneratedWelcomeOnboardWidget(),
              ),
              Positioned(
                left: 69.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 243.0,
                height: 20.0,
                child: GeneratedLetshelpyoumeetupyourtasksWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 62.0,
                child: GeneratedButtonWidget1(),
              ),
              Positioned(
                left: 27.0,
                top: 411.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 51.0,
                child: GeneratedInputWidget2(),
              ),
              Positioned(
                left: 27.0,
                top: 339.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 51.0,
                child: GeneratedInputWidget3(),
              ),
              Positioned(
                left: 27.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 51.0,
                child: GeneratedInputWidget4(),
              ),
              Positioned(
                left: 27.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 51.0,
                child: GeneratedInputWidget5(),
              ),
              Positioned(
                left: 56.0,
                top: 741.0,
                right: null,
                bottom: null,
                width: 269.0,
                height: 18.0,
                child: GeneratedAlreadyhaveanaccountSignInWidget(),
              )
            ]),
      ),
    ));
  }
}
