import 'package:flutter/material.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/Generated6Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedTasksListWidget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedTasksListWidget1.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/Generated3Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedPluscircleWidget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedShapeWidget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedGoodAfternoonWidget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/Generated9Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedEllipse13Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/Generated12Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedWelcomeMenardVegaWidget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedNotificationWidget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/vegaapp/generateddashboardwidget/generated/GeneratedGroup7Widget.dart';

/* Frame dashboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 246, 246, 246),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 307.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: -99.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 270.0,
                child: GeneratedShapeWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 324.6666564941406,
                height: 16.0,
                child: GeneratedNotificationWidget(),
              ),
              Positioned(
                left: 141.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse11Widget(),
              ),
              Positioned(
                left: 79.0,
                top: 251.0,
                right: null,
                bottom: null,
                width: 242.0,
                height: 23.0,
                child: GeneratedWelcomeMenardVegaWidget(),
              ),
              Positioned(
                left: 128.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 120.0,
                child: GeneratedEllipse12Widget(),
              ),
              Positioned(
                left: 187.13821411132812,
                top: 405.7393798828125,
                right: null,
                bottom: null,
                width: 32.56126022338867,
                height: 1.447167158126831,
                child: GeneratedRectangle25Widget(),
              ),
              Positioned(
                left: 168.231201171875,
                top: 438.5974426269531,
                right: null,
                bottom: null,
                width: 38.73063659667969,
                height: 1.377089262008667,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 187.5,
                top: 407.671142578125,
                right: null,
                bottom: null,
                width: 45.0,
                height: 1.399999976158142,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 244.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 16.0,
                child: GeneratedGoodAfternoonWidget(),
              ),
              Positioned(
                left: 183.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedEllipse13Widget(),
              ),
              Positioned(
                left: 183.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 17.0,
                child: Generated12Widget(),
              ),
              Positioned(
                left: 186.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 17.0,
                child: Generated6Widget(),
              ),
              Positioned(
                left: 238.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 17.0,
                child: Generated3Widget(),
              ),
              Positioned(
                left: 136.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 17.0,
                child: Generated9Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 23.0,
                child: GeneratedTasksListWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 528.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 248.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 18.0,
                child: GeneratedTasksListWidget1(),
              ),
              Positioned(
                left: 52.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 17.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 17.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 17.0,
                child: GeneratedGroup8Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 704.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 17.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 17.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 306.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPluscircleWidget(),
              ),
              Positioned(
                left: 317.0,
                top: 628.0,
                right: null,
                bottom: null,
                width: 3.0,
                height: 90.0,
                child: GeneratedRectangle34Widget(),
              )
            ]),
      ),
    ));
  }
}
